[workspace]
resolver = "2"
members = ["cs2kz", "cs2kz-api", "spec-generator", "macros"]

[workspace.dependencies.dotenvy]
version = "0.15"

[workspace.dependencies.color-eyre]
version = "0.6"

[workspace.dependencies.thiserror]
version = "1"

[workspace.dependencies.tracing]
version = "0.1"

[workspace.dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["std", "fmt", "ansi", "env-filter", "time", "json"]

[workspace.dependencies.time]
version = "0.3"
features = ["macros"]

[workspace.dependencies.chrono]
version = "0.4"
default-features = false
features = ["std", "serde"]

[workspace.dependencies.tokio]
version = "1"
features = ["macros", "net", "rt", "rt-multi-thread"]

[workspace.dependencies.sqlx]
version = "0.7"
default-features = false
features = ["macros", "runtime-tokio-rustls", "mysql", "chrono", "time", "rust_decimal"]

[workspace.dependencies.serde]
version = "1"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1"
