version: '3'

services:
  cs2kz-database:
    image: mariadb:11.0
    restart: no
    environment:
      MARIADB_USER: kz
      MARIADB_PASSWORD: csgo-kz-is-dead-boys
      MARIADB_DATABASE: cs2kz
      MARIADB_ROOT_PASSWORD: csgo-kz-is-dead-boys
    ports:
      - ${DATABASE_PORT:-8070}:3306
    volumes:
      - ./database/volumes/cs2kz:/var/lib/mysql

  cs2kz-api:
    restart: no
    build:
      context: .
      dockerfile: ./cs2kz-api/Dockerfile
    env_file: .env.docker
    ports:
      - ${KZ_API_PORT:-42069}:${KZ_API_PORT:-42069}
    volumes:
      - ./cs2kz-api/workshop:/kz/workshop
    depends_on:
      - cs2kz-database
