name: Staging Deployment

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Staging Instance
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Restart API
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.REPO_DIR }}
            git pull
            docker compose build --build-arg DEPOT_DOWNLOADER_URL=https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.5.0/DepotDownloader-linux-arm64.zip cs2kz-api
            docker compose up --detach --wait --force-recreate cs2kz-api
